/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.wyun.thrift.server;


import org.apache.thrift.TEnum;

public enum RESCODE implements TEnum {
  _200(200),
  _500(500),
  _400(400);

  private final int value;

  private RESCODE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RESCODE findByValue(int value) {
    switch (value) {
      case 200:
        return _200;
      case 500:
        return _500;
      case 400:
        return _400;
      default:
        return null;
    }
  }
}
